[package]
name = "sanma_engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]        # produce a shared library PyO3 can wrap

[dependencies]
numpy = "0.21.0"
pyo3 = { version = "0.21.2", features = ["extension-module"] }
rand = "0.8.5"